# Generated by Django 4.2.1 on 2023-06-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("website", "0002_auto_20230604_0908"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nachrichts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(auto_created=True, null=True),
                ),
                ("name", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.TextField(null=True)),
                ("message", models.TextField()),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
